header:
  license:
    content: |
      Copyright (c) Meta Platforms, Inc. and affiliates.
      
      This source code is licensed under the MIT license found in the
      LICENSE file in the root directory of this source tree.
    pattern: |
      (?s)(Copyright \(c\) Meta Platforms, Inc\. and affiliates\.\n+
      This source code is licensed under the MIT license found in the
      LICENSE file in the root directory of this source tree\.)|
      (Copyright \(c\) Meta Platforms, Inc\. and affiliates\.\n+
      All rights reserved\.\n+
      This source code is licensed under the license found in the
      LICENSE file in the root directory of this source tree\.)
  paths:
    - "**/*.py"
    - "**/*.sh"
  comment: never
